'use strict';

const express = require('express');
const router  = express.Router();

const { guard }           = require('../config/routePermissions');
const requireReportAccess = require('../middleware/requireReportAccess');
const ReportingCntlr      = require('../controllers/ReportingCntlr')();

/**
 * Reporting router — a generic surface over the report registry. Individual
 * reports are self-contained controllers in controllers/reports/; no
 * per-report route is ever added here.
 *
 * Access control is per report CATEGORY: the catalog route needs any report
 * permission (and filters to what the caller holds); every :slug route is
 * narrowed to the addressed report's own category permission at request time
 * by requireReportAccess.
 */

// Catalog — categories and reports visible to the caller.
router.get('/', guard('GET /api/v1/reports'), ReportingCntlr.catalog);

// Immediate reports: execute and return rows in-request.
router.get('/:slug/results', requireReportAccess(), ReportingCntlr.results);

// Stored reports (scheduled and/or long-running): queued runs generated by a
// background process, then listed / viewed / downloaded.
router.post('/:slug/runs',                  requireReportAccess(), ReportingCntlr.startRun);
router.get('/:slug/runs',                   requireReportAccess(), ReportingCntlr.listRuns);
router.get('/:slug/runs/:run_no',           requireReportAccess(), ReportingCntlr.getRun);
router.get('/:slug/runs/:run_no/download',  requireReportAccess(), ReportingCntlr.download);

module.exports = router;
