'use strict';

const fs   = require('fs/promises');
const path = require('path');

/**
 * Filesystem adapter for the image-store port: bytes under backend/uploads/,
 * served by the API's own /images static mount.
 *
 * The default, and correct for the single-instance deployments in README §2.
 * Files are local to one machine, so any deployment running more than one API
 * instance needs a shared store instead — see s3Adapter.
 *
 * Knows about bytes and paths only; image naming is the caller's (policy.js).
 */
const LocalImageAdapter = (function () {

    const ROOT = path.join(__dirname, '../../uploads');

    return { provider: 'local', root: ROOT, put, remove };

    /** Writes an image, creating the per-product directory on first use. */
    async function put(key, _mimetype, buffer) {
        const abs = resolveWithinRoot(key);
        if (!abs) throw new Error(`Refusing to write an image outside the uploads root: "${key}"`);
        await fs.mkdir(path.dirname(abs), { recursive: true });
        await fs.writeFile(abs, buffer);
    }

    /** Removal is idempotent — a file already gone is not an error. */
    async function remove(key) {
        const abs = resolveWithinRoot(key);
        if (!abs) return;
        await fs.unlink(abs).catch(err => { if (err.code !== 'ENOENT') throw err; });
    }

    /**
     * Absolute path for a key, or null if it escapes the uploads root. Keys
     * are generated by policy.js, but they round-trip through the database
     * before a delete, so a corrupted or hand-edited row must not be able to
     * reach the wider filesystem.
     */
    function resolveWithinRoot(key) {
        if (!key) return null;
        const abs = path.resolve(ROOT, key);
        return abs.startsWith(ROOT + path.sep) ? abs : null;
    }

}());

module.exports = LocalImageAdapter;
